name: iso
description: An isolates runner that handles bidirectionnal communication. Run
  some code in an isolate and communicate with it
homepage: https://github.com/synw/iso
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  extra_pedantic: ^1.3.0
  meta: ^1.3.0
  pedantic: ^1.11.0

dev_dependencies:
  test: ^1.17.3
